#!/usr/bin/env ruby -W0
#coding=utf-8

#
# if $PROGRAM_NAME == __FILE__
#   ENV['BUNDLE_GEMFILE'] = File.expand_path('../Gemfile', __FILE__)
#   require 'bundler/setup'
# end

require_relative 'lib/m-git'


module MGit
  extend self

  SRC_ROOT = __dir__
end

MGit.run(ARGV)
